language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: BpxfTxY1SbO22PStJwRxnc6ZThiJGjqE4ZMMSED6y5KPeHEhG0SXIdmcz0ciRds6SZ7YUcJeD5F5yb6DAXdpvZhNXbPs5vTs/ZGlYFbRTJoVOuJfeIRVQjxjPpHFFuEdVVDF19VP5pSflorZoIXbNq8SWsN6QwM71pEbTvA9MlvLzDqEaZjKS5Eu+SnECaUQUQV5z+WsrtWeTBdX4azfA/0tJe6aOTj6jTQ1n0nV3JBGCj8VrYf7+ldQpbZLooud38WIJKgmwDUsqXzRzZlWAfOcDaa7TCgIE+i+hgPlduwxOlhdf9U5VYDyp0N8dpHHJ90D+JdC7T8FXA40M0F+BBczdnFDLu0U5jq22F00ByTng/vPOtQD2PxM0n8PxrzZ+7NyPXQFWy/VIREJURGJ1Tc95K6obZMvzE/A++JssGHgNDKiTeMpbukZOsWK8IB8ywXgBNqPKaBX6Q6NDgjE4cwaJeYrvyZaAfajcmBmOzVNXCMz53rLgMLcbh2kO5kw0/UKC+BL3LIA1qbG0eN5rcPufBbzFgHWuKmpHz7Vj9m3iVjXrYI/3OG1NOgPpH7Hya2ZEaNl1Djblx8AMJoBPSKodfFomznes6z/Ex8JAj5cgdr5W0bT4DBpmMjhhMdbCa+z3V1jxbNr76SQJ8kNlqTtn33ymiOsZPl4Z1UDfGM=
  app: young-caverns-78168